services:
  app:
    build: .
    ports:
      - "8001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules 
    command: ["npx", "next", "dev"]
    restart: always
